### PR TITLE
feat: make commit message configurable

### PR DESCRIPTION
**Pull request by sukovanej**

### CODE REVIEW

**Comment by jpb06** [comment]
Hello. Thank you for your contribution. 

Sadly, there seems to be no way to run sonar from forks pull requests, so I will just go ahead and merge this.
CF https://community.sonarsource.com/t/code-analysis-on-pull-request-from-forked-repository-with-github-actions/43986/6

**Comment by jpb06** [comment]
Released as [1.9.4](https://github.com/jpb06/jest-badges-action/releases/tag/v1.9.4)

**Comment by sukovanej** [comment]
FYI, I just tested it on my repo, works as a charm. Thanks a lot!

**Comment by jpb06** [comment]
Great, thanks 🙇🏻

**Pull request merged**
